### ISSUE TITLE
Implement Android's notification channels

### ISSUE THREAD

**Issue by loxK** [UP-NextPush/android#101]
Implement Android's notification channels in order to independently manage UnifiedPush notification (ringtone, vibrate etc.)

https://developer.android.com/develop/ui/views/notifications/channels

**Comment by p1gp1g** [comment]
There are already 3 different channels :
- One for the foreground service's notification
- One for the warning notifications
- One for the in-app pushed notifications (those not forwarded to other apps)

**Comment by loxK** [comment]
Isn't it possible to have an Android notification channel for each manually created endpoint ? I have a type of notification that needs a strong ringtone, but not the others.

**Comment by p1gp1g** [comment]
I see, that is possible

**Comment by p1gp1g** [comment]
This is done, and will be in next release.

PS: I've unarchived this issue to resolve it. Development as moved to Codeberg.
