### ISSUE TITLE
Unclear how this app works - does seem to behave as expected

### ISSUE THREAD

**Issue by mdeweerd** [UP-NextPush/android#102]
I've installed the app but other than showing "Notification to run in foreground", I can't find any method to make it useful.

I have NextPush 1.8.1 and Nextcloud 3.26.0 on my phone and Nextcloud Server 27.1.4.

- I have a permanent notification in my notification list: "Notification to run in foreground" : not sure if I can get rid of this or if this has to be there;
- When I open Nextpush I have:
  - Nextpush title;
  - Access to menu: Restart Service / Logout / Add notification Channel;
  - Account: You are connected to ...
  - *Registered applications* - No applications are listed.  I've added several notification channels but I do not know how I can see that.

Supplementary question: is there a method to see the registered applications on the Nextcloud Server?

**Comment by p1gp1g** [comment]
Try [UP-Example](https://f-droid.org/fr/packages/org.unifiedpush.example/)

**Comment by mdeweerd** [comment]
> Try [UP-Example](https://f-droid.org/fr/packages/org.unifiedpush.example/)

Thank you for pointing me in the direction of an app, but as far as I understood I should be able to add an notirivation channel, click on it to get the endpoint and test it using curl.

However, when I add a notification channel, nothing changes, when I restrat the application, nothing changes.

So is there a way to see any created notification channel on the server (to verify that the creation worked).
Is it normal for created notification channels to NOT appear in the NextPush application where I created them?

**Comment by p1gp1g** [comment]
What do you want to do ? If you want to use NextPush as an UnifiedPush distributor, then you have nothing to do on the app. That why I suggest you to try the example. Else, could you provide screenshots of what you are doing ?

**Comment by mdeweerd** [comment]
I just managed to identify that `uppush` needs to be installed on the nextcloud instance.

In interpreted "Server App Install" as the installation of the Nextcloud Server Application itself. 
 Labeling this differently would help.
Also, I wonder why the application does not report an issue when creating the channel when the Uppush application is not installed.
~~Now I that I created a channel, I long pressed on it, copied but I did not get the URL.~~ EDIT: tried again - worked - would be nice if this triggered the sharing functionnality on the phone.
The server app does not provide a liste of created channels (or channels that apps subscribted to).

**Comment by p1gp1g** [comment]
> Also, I wonder why the application does not report an issue when creating the channel when the Uppush application is not installed.

Can you open an issue for this ? :)

> The server app does not provide a liste of created channels (or channels that apps subscribted to).

You should check again

**Comment by mdeweerd** [comment]
I opened another issue for the lack of a message indicating the Push Provider is not installed in Nextcloud, so I am closing this one.

I tested the push notifications using curl and those work.
