### ISSUE TITLE
The application does not report an issue when creating the channel when the UnifiedPush provider app is not installed.

### ISSUE THREAD

**Issue by mdeweerd** [UP-NextPush/android#105]
As explained in #102 I was puzzled by the application not doing anything useful as I was logged in and when adding channels, nothing happened.

In fact the the application does not report an issue when creating the channel when the Uppush/Unified Push Provider application is not installed on the server.

It would be helpful for new users to notify about this - and possibly also for cases when the application was removed or disabled (incompatible) on the server.

_Originally posted by @p1gp1g in https://github.com/UP-NextPush/android/issues/102#issuecomment-1836224233_

**Comment by p1gp1g** [comment]
This is done, and will be in next release.

PS: I've unarchived this issue to resolve it. Development as moved to Codeberg.
