### ISSUE TITLE
Basic instructions on how to use

### ISSUE THREAD

**Issue by Bugsbane** [UP-NextPush/android#13]
Hi there,
I have nextcloud working fine, and the Unified Push Provider app installed on it. On my phone I have Nextcloud Push, Fedilab and Fluffychat installed.

Both the Unified Push Settings on the server and the NextPush settings on the phone app show no applications registered.

I have no idea if I have set things up correctly, or if I've hit a bug, because I haven't been able to find instructions after hours of research, as to how to get started using UnifiedPush. I 've read the pages on UnifiedPush.org, and on FluffyChat and Fedilab's pages, but none of them give a step by step on what needs to be done, even in a general sense.

It would really help to have some very basic instructions in the readme.md file as to how to get started, eg:

1. Install Unified Push Provider app in your Nextcloud server instance
2. Install Nextcloud Push app on an Android phone from Google Play or FDroid
3. Make sure you have one or more UnifiedPush compatible apps installed on your phone (eg FluffyChat/Fedilab).
4. ????
5. You should now be getting UnifiedPush notifications on your phone.

**Comment by p1gp1g** [comment]
0. Make sure your nextcloud server uses redis
1. Install Unified Push Provider app in your Nextcloud server instance
2. Install Nextcloud Push app on an Android phone from Google Play or FDroid
3. Make sure you have one or more UnifiedPush compatible apps installed on your phone (eg FluffyChat/Fedilab). __You can try UP-Example to see if everything works__
4. You should now be getting UnifiedPush notifications on your phone.

**Comment by Bugsbane** [comment]
Thanks. So it seems that there's a bug somewhere in the mix rather than just a setup problem. I've filed a separate issue.

**Comment by tonytonyistony** [comment]
How do you connect from Fluffy Chat? I have everything working up to using the UP-Example and it sends a test notification properly. Ive tried Fluffychat, Schildichat, Fedilab and none will connect to my NC instance using the URL "https://nc.example.com"

Ive been banging my head against the wall on this for days, and I cant seem to figure it out.
I agree with @Bugsbane, better, more detailed instructions would be greatly appreciated.

**Comment by tonytonyistony** [comment]
"You connect Fluffychat to your matrix server (let's say matrix.org)"

What matrix server?
Can you show me an example of a URL if I was hosting my own Matrix relay?
I have no idea what to put into fluffychat.

I also put in a PR to update the Readme for this app and the server.

**Comment by p1gp1g** [comment]
> "You connect Fluffychat to your matrix server (let's say matrix.org)"
> 
> What matrix server? Can you show me an example of a URL if I was hosting my own Matrix relay? I have no idea what to put into fluffychat.

https://matrix.org then click on "connect" if you already have an account, "register" else. You don't have to set anything related to nextpush/unifiedpush on fluffychat. Fluffychat will automatically request an endpoint to NextPush to send notifications to
