### ISSUE TITLE
NextPush shows noitifications for both "Listening" and "Disconnected" at the same time.

### ISSUE THREAD

**Issue by Bugsbane** [UP-NextPush/android#14]
I have Nextpush installed on my Nextcloud server, which is using Redis and is available by HTTPS. I have NextPush, Nextcloud, UP-example and Fluffychat installed on my phone.

- NextPush says it's connected to my user on my Nextcloud.
- It says that Fluffychat and UP-example are registered with it.
- It has a notification that says "Listening for incoming notifications" and it also has a second notification that says "NextPush is disconnected" which comes up almost immediately after restarting.
- I don't seem to get any notifications.
- UP-example says that it's registered

Any further info I can supply to debug?

**Comment by p1gp1g** [comment]
That's a wording problem. The first notification is for the foreground process, the second to inform about not connected app

**Comment by p1gp1g** [comment]
https://github.com/UP-NextPush/android/commit/e8ce207517a8d16d7536129c748789073b41a97b fixes it
