### ISSUE TITLE
Repeated notifications when there is a connection issue

### ISSUE THREAD

**Issue by akallabeth** [UP-NextPush/android#32]
Got some connection issues with my nextcloud instance since yesterday.
The notification of nextpush is very annoying (and prevents disabling it)

1. The notification occurs every ~second hiding the menu options to logout from nextpush
2. When clicking the notification there is no way to disable it until resolved

only way I found was starting the app settings and kill it

**Comment by p1gp1g** [comment]
Which version of NextPush do you use ? And can you provides some logs ? Remember to redact UUIDs from the logs

**Comment by akallabeth** [comment]
* I´ve installed 1.3.0 from https://f-droid.org/en/packages/org.unifiedpush.distributor.nextpush/
* Os is GrapheneOS without any google services installed

the connection issue has been resolved now, so no logs, sorry :/
but the issue was not that but that (the connection issue was real), but that the notification did repeatedly show so that it always hid the options to restart/logout within the app.

**Comment by p1gp1g** [comment]
>  but that the notification did repeatedly show so that it always hid the options to restart/logout within the app.

That's why I wanted the logs, to know what happened. The notification must be there without spamming :)

If you experience it again, or find a way to reproduce, could you try to catch some plz :)

**Comment by p1gp1g** [comment]
Did it happen again ?

**Comment by akallabeth** [comment]
@p1gp1g sadly that on I could not reproduce.

**Comment by p1gp1g** [comment]
We may close this issue and openning it later again if needed

**Comment by akallabeth** [comment]
Yes, still failed to reproduce.
