### ISSUE TITLE
Error about missing nextcloud app (≈ support beta?)

### ISSUE THREAD

**Issue by tennox** [UP-NextPush/android#52]
I've installed nextcloud beta through f-droid (At least I'm guessing the beta part is the issue...?)

And after tapping login button and selecting my account i get this:

![Screenshot_20221011-235749_NextPush__01.png](https://user-images.githubusercontent.com/2084639/195214491-5b97b13e-dea7-40c5-8d14-e12555ec5db1.png)

Using latest nextcloud beta
![Screenshot_20221011-235814_Nextcloud__01.png](https://user-images.githubusercontent.com/2084639/195214535-3784c123-a4f5-4da2-8182-cb45d8e07249.png)

**Comment by p1gp1g** [comment]
That is an issue with the nextcloud Android-SSO library https://github.com/nextcloud/Android-SingleSignOn/issues/470

**Comment by p1gp1g** [comment]
- 1.5.0 allows manual (non-SSO) connection. That means you can use nextpush without the Nextcloud App
- The SSO not working with the beta app is on the lib side. 

So I think it is fair to close this issue, let me know if you don't think so :)
