### ISSUE TITLE
Battery usage

### ISSUE THREAD

**Issue by barathrm** [UP-NextPush/android#58]
Since installing and using nextpush for my push notifications (element and fluffychat on the same phone) it's now the app using most of my battery, according to android. Alledgedly it's been "used" for about 12 hours, and I installed and started using it a bit less than 24 hours ago. Android says it responsible for 22% of my battery usage overall. I've set it to "unrestricted" under battery optimization.

Let me know if you want any other debug info. For now it seems like using element + polling is easier on the battery usage.

**Comment by karmanyaahm** [comment]
What device/OS version do you have?

**Comment by barathrm** [comment]
Google Pixel 4a running GrapheneOS. I'll compare to ntfy usage and test nextpush a bit longer after the holidays if that helps.

**Comment by p1gp1g** [comment]
You probably have an issue with your connection timeout. Can you paste your reverse proxy config ? Do not forget to anonymized it. (Doc: https://github.com/UP-NextPush/server-app#installation)

**Comment by p1gp1g** [comment]
If you don't want to edit config file, go to the admin settings > unifiedpush (not the user one !) and set timeout to 50 seconds

**Comment by barathrm** [comment]
Thank you for the tips. I based my nginx reverse-proxy config on the docs you're linking to, so I had those timeouts configured. I'll double-check those and the app-internal timeout when I try nextpush again after I've tried ntfy for a bit.

**Comment by rickcrash** [comment]
Same thing here. My nextcloud  Server runs on lighttpd, my mobile on grapheneos without any google-aervice.

Everything worked well with Version 1.4.3 but with Version 1.5.0 there is a huge battety darin. So I Bad to reinstall 1.4.3. I got all veesions fron f-Droid.

**Comment by aitorpazos** [comment]
Seeing pretty high battery usage in 1.6.3. It is the top 1 battery consumer in my phone atm.

**Comment by p1gp1g** [comment]
> Seeing pretty high battery usage in 1.6.3. It is the top 1 battery consumer in my phone atm.

Do you have any notification saying there is an issue with your config ? Could you copy/paste the debug info ? (tap 5 times on "Account")

**Comment by p1gp1g** [comment]
You have an issue with your proxy keepalive. If you want to keep a long keepalive, you have to configure your proxy. Else, you can set the keepalive to 50 in the unifiedpush admin setting (nextcloud), it should work

**Comment by p1gp1g** [comment]
This issue is very probably related to all-in-one. The fix is available in the beta channel: https://github.com/nextcloud/all-in-one#how-to-switch-the-channel, So I'm closing it.

(PS: development has moved to codeberg: https://codeberg.org/NextPush)
