### ISSUE TITLE
Alternative login without using the SSO

### ISSUE THREAD

**Issue by IzzySoft** [UP-NextPush/android#7]
As mentioned on [the review for F-Droid inclusion](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10129#note_755627582), it would be nice if the dependency on the Nextcloud app (30M APK) could be lifted in favor of their [SSO module](https://github.com/nextcloud/Android-SingleSignOn). While many who use Nextcloud will have the app installed, others have not (like me) as they e.g. just use Davx⁵ for calendar and addressbook sync on the device – and thus requiring the full Nextcloud app just to have notifications would be quite some overkill.

An examples with the same issue would be [Nextcloud Maps](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9655), if you want something to compare: it started requiring the Nextcoud app and in the process switched to the SSO lib.

Thanks for considering!

**Comment by p1gp1g** [comment]
I just edit this issue name because it is the opposite : NextPush currently only use the SSO lib (which intent the Nextcloud app to do requests) and does not provide an alternative way to login.

**Comment by IzzySoft** [comment]
Now I am confused. I remember several other apps connecting to Nextcloud, where at least one originally depended on the Nextcloud app being installed on-device and then switched to a stand-alone variant of the SSO library (at least that's what I understood). As I expect more cases like that to show up, I'd welcome some "enlightenment" to understand it correctly (so I can give the right hints). The SSO lib is not stand-alone, but depends on the Nextcloud app? Which one is the "independent" lib then? Thanks!

Oh, and of course thanks for taking care!

**Comment by p1gp1g** [comment]
It seems there are two libraries :
* [The nextcloud lib](https://github.com/nextcloud/android-library)
* [The SSO](https://github.com/nextcloud/Android-SingleSignOn)

As mentionned [in their doc](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/android_library/index.html#android-nextcloud-client-development), the SSO lib require the Nextcloud app to be installed. ([cf. The flow diagram](https://github.com/nextcloud/Android-SingleSignOn#flow-diagram))

**Comment by p1gp1g** [comment]
That's finally done with 1.5.0 ! It was more work than expected :')

**Comment by IzzySoft** [comment]
Thanks a lot! Then I can give it a try again as soon as time permits :star_struck:
