### ISSUE TITLE
Nextpush disconnected warning when WiFi and cell data are disconnected

### ISSUE THREAD

**Issue by provokateurin** [UP-NextPush/android#74]
This warning is useless to users since it is expected that NextPush is not connected in those cases.

**Comment by p1gp1g** [comment]
It is fixed with v1.6.0 :)

**Comment by provokateurin** [comment]
For me it was already fixed in 1.5.1 🤔

**Comment by p1gp1g** [comment]
Hm that's weird.

Nevertheless, 1.6.0 do not show warning nor try to reconnect until the Internet is available again. It will reduce battery drain when there is no Internet at the same time.

**Comment by provokateurin** [comment]
Awesome!
I was also confused why the notification wasn't shown anymore because I looked at the commits and there was nothing that indicated it was fixed :woman_shrugging:

**Comment by p1gp1g** [comment]
Are you sure you haven't disable the warning notification ?

**Comment by provokateurin** [comment]
Oh wait I was just confused haha. It's still there, I just made it silent and apparently managed to completely forget about it...
